// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPageWebApp.Models;

namespace MultiPageWebApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210211203051_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiPageWebApp.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Number")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "512 Tire Street",
                            Name = "Billy Bob",
                            Note = "Lives on a street named after a tire",
                            Number = 8482736436L
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "718 Street Boulevard",
                            Name = "Dage Gecker",
                            Note = "Odd Name and Street.",
                            Number = 8847362396L
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "514 Plop Drive",
                            Name = "Bob Billard",
                            Note = "Likes Pool",
                            Number = 9482736436L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
